### PR TITLE
Add support for running from Unicode install path.

### PR DESCRIPTION
**Pull request by adiroiban**
Scope
=====

Allow brink to be used with Unicode install paths.

Changes
=======

Add required code to have brink execute from a unicode path.

As a drive by, I have f fixed the code coverage reporting.

As a drive by, I have updated brink-pip to use the global cache, rather than the REPO/cache directory.

The build dir is now always "build/" on all OSes.

-------

It looks like on Windows, the Python.exe is not working with Unicode path... so for Windows we might only fix it with Python3 migration.

```
buildslave@bs3n-win-2019-x64-125 MINGW64 ~/chevah/bs/brink-win-i18n/build/build-ț (unicode-path)
$ ./lib/python
ImportError: No module named site
```

How to try and test the changes
===============================

reviewers: @dumol 

FYI  See the change in paver.sh. If paver.conf has a non-empty BUILD_FOLDER, it will be used as the build dir.

This is also a FYI for the state for brink slaves.

Brink is the first repo that was added to GitHub actions. You can see the result at https://github.com/chevah/brink/pull/119/checks

### CODE REVIEW

**Comment by adiroiban** [comment]
@dumol this is more of a FYI.

I have used this PR as an experiment with GitHub actions.

It was easy to add a new "github-runner" https://github.com/chevah/brink/settings/actions

Working with GitHub actions is much easier than buildslave, as everything is defined inside the repo / branch / PR

For now, there is no need to make any changes to Unicode paths in buildslaves.

I think that we can slowly replace some buildslave with GitHub Action runner and then it will be much easier to run tests with Unicode paths.

needs-review

**Comment by dumol** [comment]
Thanks! Have added some more Python module updates in `pavement.py`, to minimize the need for `./paver.sh deps` when using common `cache/` and `build-*` sub-dirs.

Still, I don't know how `buildbot-0.8.11rc7` is pulled here… It should be updated to `buildbot-0.8.11.chevah11` as well.

**changes-approved**

**Comment by adiroiban** [comment]
I have updated the code to have configurable cache.

I have also updated so that DEFAULT_VALUES file is no longer needed

Please check that the cache work as expected... we will need to update buildbot to use brink.sh and to also define a custom CHEVAH_CACHE for each slave

needs-review

**Comment by dumol** [comment]
Fine by me. Looking forward to `CHEVAH_CACHE`…

Maybe even a `CHEVAH_BUILD` env var? I have `build-brink/` symlinked to a shared `build-obsd66-x64/`, and things still work for me as expected. There are greater disk space savings from the shared build sub-dir.

**Pull request merged**
