### PR TITLE
[#4085] Fix RQM so that it can merge the branch.

### PR DESCRIPTION
**Pull request by adiroiban**
Scope
=====

With the new change in PQM where we use github protected branches, the RQM fails as the merge commit is not tested.

Changes
=======

Use GitHub API to do the merge.

How to try and test the changes
===============================

reviewers: @hcs0 

Testing this is hard as he change is basically irreversible... and to reverse it you need to disable branch protection.

Send this branch to RQM  for landing on production and if successfully merged, then all is good.

Before the final send you can try to push changes and push before all tests were done, or before the review is done.

You can check the previous PR  like #110 and the buildbot logs

### CODE REVIEW

**Comment by adiroiban** [comment]
changes-approved

**Comment by adiroiban** [comment]
needs-review

**Comment by adiroiban** [comment]
needs-review

**Comment by hcs0** [comment]
Testing this out by pushing a change, no approval from reviewer then sent the branch to RQM.
Looks like one test is failing though.  So I don't think this branch will merge to master anyway because of the failed tests.

**Comment by adiroiban** [comment]
aix-61 is failing, as it was recently introduced by Misu... but aix-61 is not required... so it will merge.

For now: `Merging can be performed automatically with one approved review.`

**Comment by hcs0** [comment]
I've approved this PR.
I am sending this to RQM again.  I'm currently only running ``paver rqm`` on the branch

**Comment by adiroiban** [comment]
just using `paver rqm` will not help, as it will send it to staging... and staging is already working.

here I am trying to fix the RQM on production, which will auto merge and auto-create the tag.

testing this is hard for chevah/server and we would only be able to test it with the next release :)

**Comment by adiroiban** [comment]
but feel free to send this to RQM in production, and see how it will be merged... as this is what we are expecting to see in production

--------

there is still one issue, in that the tag is not created... and I don't know what is wrong as using the GitHub API i see that the tag is there... but is not refleted in Git

**Comment by hcs0** [comment]
Just sent to rqm again.
``./paver.sh rqm --target=production --pull-id=111``

**Comment by adiroiban** [comment]
so it failed ... with a strange error https://chevah.com/buildbot/builders/brink-gk-release/builds/11/steps/merge-commit/logs/stdio

```
405 {u'documentation_url': u'https://help.github.com/articles/about-protected-branches', u'message': u'Waiting on code owner review from adiroiban.'}
```

I am the PR owner... and GitHub Merge thinks that I should review my own code.... but GitHub does not allow to review my own code.

I think that this is a bug in GitHub

**Comment by adiroiban** [comment]
I have sent a bug report to GitHub and for now I have disabled the code owner protection. Will send this to PQM to production... and then we should see a tag and this auto-merged

**Comment by adiroiban** [comment]
So it was accepted. Thanks for the review!

I have released brink 0.64.0

@hcs0 maybe we can do a quick bugfix release in SFTPPlus, just to practice the updated release process. What do you think?

**Comment by hcs0** [comment]
Sounds good

**Pull request merged**
