### PR TITLE
[#4144] Update paver from python-package.

### PR DESCRIPTION
**Pull request by dumol**
Scope
=====

Get latest changes to `paver.sh` for specific support for Raspbian 8.

Changes
=======

Copied over `paver.sh` from `python-package` with changes broken for readability.
Updated configured `python-package` version for Raspbian 8 and Ubuntu 16.04 arm64.

How to try and test the changes
===============================

reviewers: @adiroiban 

Please review the changes.
Run the tests.

### CODE REVIEW

**Comment by dumol** [comment]
**needs-review**

**Comment by dumol** [comment]
This needs updated production python packages to pass tests.

**needs-changes**

**Comment by dumol** [comment]
**needs-review**

**Comment by adiroiban** [comment]
I have moved one last change... which I think it useful as it makes the paver.conf more flexible.

In the end I hope that we can move paver.conf and paver.sh into a separate repo and try to promote it as a tool for python bootstraping

**Comment by dumol** [comment]
Hhhmmm, I see there are already more changes in #97, versioned as 0.61.4… I think it would be best to let that hit master, then merge with master here, and only then commit the changes of this branch to master.

@adiroiban, what do you think?

**Comment by adiroiban** [comment]
For now #97 is at a dead end ... so I think that we should merge this first.

Thanks!

**Comment by adiroiban** [comment]
Sorry for the noise.

@dumol for chevah/brink we will no longer use PQM, but just use the GitHub merge button.

PQM was set up to protect the master branch, but now we have GitHub protected branches.
I find them much easier to use, and is less work for me in maintaining the PQM code.

Please merge this PR using the GitHub merge button.

Thanks!

**Comment by dumol** [comment]
Thanks! Let's see… :-]

**Pull request merged**
