### PR TITLE
[#3732] Update README with paver repository information

### PR DESCRIPTION
**Pull request by dispera**
Scope
=====

Add information on README file regarding paver repository.

Changes
=======

Documentation update.

Reviewers
========

reviewers: @adiroiban

### CODE REVIEW

**Comment by dispera** [comment]
Added the reference on this repository regarding paver.sh, as we discussed before on the trac ticket.

needs-review

**Comment by adiroiban** [comment]
thanks!

this looks good.... for the near future, maybe we should also update paver.sh script itself to include a comment pointing to the place from where it can be updated 

changes-approved

**Comment by adiroiban** [comment]
ups... needs-changes

this PR is linked to #3732: Add solaris10u3 OS to paver

this seems wrong :(

**Comment by dispera** [comment]
I made it part of #3732 because of what I understood from a comment earlier on that track ticket:
"We can use 3732 as a ticket to remind us to update paver.sh in brink... but we might just want to update the chevah/brink README to talk that the source of paver.sh is chevah/python package."

But I should have changed the trac ticket name too when the main task changed :)

I updated the PR name now, to avoid confusion, as it seemed wrong indeed as it was.

needs-review

**Comment by adiroiban** [comment]
> I made it part of #3732 because of what I understood from a comment earlier on that track ticket:
> "We can use 3732 as a ticket to remind us to update paver.sh in brink... but we might just want to update the chevah/brink README to talk that the source of paver.sh is chevah/python package."

Well, my comment was about the fact that for a such small change we don't need a separate ticket, and while working on a soon to be reviewed ticket we can update the readme as a drive by fix

**Comment by adiroiban** [comment]
thanks.

changes-approved

**Pull request merged**
