### PR TITLE
[#2765] Fix approval detection for a review.

### PR DESCRIPTION
**Pull request by adiroiban**
Problem
=======

the current code has a problem.
let's say we have 2 reviewers: A B and Developer D
D > needs-review
A > changes-approved
B > needs-changes
B > changes-approved
the review is accepted but I think that developer A should do a review of the changes

Changes
=======

Change code to reject a review as soon as it see a needs-changes tag

How to test
========

reviewers: @alibotean  @adiroiban

Enter comments similar to described problem

### CODE REVIEW

**Comment by adiroiban** [comment]
needs-review

**Comment by alibotean** [comment]
changes-approved

**Comment by adiroiban** [comment]
needs-changes

**Comment by adiroiban** [comment]
needs-review

**Comment by adiroiban** [comment]
changes-approved

**Comment by adiroiban** [comment]
Looks good... 

I sent it to PQM and it was rejected http://build.chevah.com/builders/brink-gk-merge/builds/43/steps/merge-init/logs/stdio

it the pass it was accepted

**Comment by adiroiban** [comment]
btw... this is ready for review

**Comment by alibotean** [comment]
changes-approved

**Comment by adiroiban** [comment]
plase check latest fix... I have recently modified the buildbot to also run osx tests for brink and I found a problem... it is known Unicode normalization problem on OSX.

**Pull request closed without merging**
