### PR TITLE
[#2816] Fix PQM merge in GitHub.

### PR DESCRIPTION
**Pull request by adiroiban**
Problem
======

PQM is designed to only push to private repo

Changes
=======

Update code to allow pushing to GitHub URI without exposing the token ID.

Buildbot repos are a beast since they only care about the SHA commit... they don't care about branches/remotes/repos .. etc

As a drive by I have updated the URL used by `github  new`

As a drive by you can now use `test remote BUILDER --force_clean` and will automaticlaly trigger the clean step on the remote builder.

I have updated the python git package just in case they fix any bug.

I have clean the review command as we have no plan to support ReviewBoard in the future

How to test
========

reviewers: @alibotean 

this is just to let you know about the changes.

brink 0.54.4 is already released and I used to to merge a branch in server repo.

### CODE REVIEW

**Comment by adiroiban** [comment]
needs-review

**Comment by adiroiban** [comment]
changes-approved

**Comment by adiroiban** [comment]
needs-review

**Comment by alibotean** [comment]
changes-approved

**Pull request closed without merging**
