### PR TITLE
[#4905] Update Windows dev distribution for git-lfs and store buildbot credentials in external files.

### PR DESCRIPTION
**Pull request by adiroiban**
Scope
=====

This is an update for the Windows dev environment to have rsync and git-lfs.

Changes
=======

Create a new archive with git-lfs and rsync.

Add documentation to the archive (version file, readme files)

Simplify the msys-console.js script.

This also adds support for sha256 checksum as an update to md5.

How to try and test the changes
===============================

reviewers: @lgheorghiu 

@lgheorghiu you should download the msys-console.js script from this branch and run it.
It should create a new dev environment which has git-lfs and rsync and ssh-rsync

@lgheorghiu you should uninstall git-lfs if you have it manually installed.

Let me know if other tools needs to be installed.

---------

@dumol please check that paver.conf is ok... is the same as in compat now :) 

I added as a reviewer just to know that you Windows base env was updated.
You can give it a try on Windows VM, or just wait for when a new Win VM can be created.
The git version is the same, this just adds extra tools.

1.Publish to staging from Windows
----------------------------------

In a branch on chevah/server or sftpplus.com modify paver.conf to have `chevah-brink==0.69.2`
Then run paver.deps

You will need to create `c:\users\YOUR-USER\.ssh\config` file and add Port for the staging.sftpplus.com as documented in the README from sftpplus.com

the content of `.ssh\config` for Windows
```
UserKnownHostsFile c:\Users\YOUR-USER\.ssh\known_hosts
Host staging.sftpplus.com
    Port 12022
    IdentityFile C:\Users\YOUR-USER\.ssh\id_rsa
```

`C:\Users\YOUR-USER\.ssh\id_rsa` is the path to the SSH key which you configured to allow uploads.

Then try `paver publish --target=staging` on a SFTPPlus.com branch or `paver publish_documentation` on chevah/server branch.

### CODE REVIEW

**Comment by adiroiban** [comment]
Thanks. The "required" builds can be configured from here https://github.com/chevah/brink/settings/branches/master.

Yes. We can enable Solaris 11 on x86.

**Comment by adiroiban** [comment]
@dumol can you please copy /home/chevah/git-windows-x86-2.11.0.chevah2.zip on deag to buildmaster so that it will reach binary.
My PGP setup is broken now and I can't get the root password for deag :)

-------------

@lgheorghiu once you can see git-windows-x86-2.11.0.chevah2.zip https://binary.chevah.com/production/msys-console/ please get the new msys-console.js or update your msys-console.js to have chevah**2**.zip version and give a a try.

Check the updated description for how to set up the `.ssh/config` file.

needs-review

**Comment by dumol** [comment]
Done.

**Comment by dumol** [comment]
`paver.conf` changes look fine.

**changes-approved**

**Comment by lgheorghiu** [comment]
@adiroiban I'm failing to make it run. I'll wait for you to get back tomorrow so we can have a look together.

**Comment by adiroiban** [comment]
@lgheorghiu please give it a try with  0.69.4 

The work is not perfect, but I hope is good enough for using it on staging.

Please check if git-lfs works on your side... on my system the images where not uploaded as they were git-lfs.

needs-review

**Comment by lgheorghiu** [comment]
Tested with the 0.69.4 on a sftpplus.com branch (sftpplus.com (4867-ipv6-preparedness-filet
ransfer)). Ran paver publish --target=staging and got the following error:
```
Sending to staging... yeovil.sftpplus.com staging.sftpplus.com/
rsync: -no-p: unknown option
rsync error: syntax or usage error (code 1) at main.c(1578) [client=3.1.3]

```

**Comment by dumol** [comment]
No pressure, but isn't this fixed already? Why is it not merged?

Itching to close a ticket of time that depends on this: https://trac.chevah.com/ticket/4723.

**Comment by adiroiban** [comment]
This is not fixed as I was also trying to get rsync.

A brink version from this branch is already released and used in production.

I think that for dev, we now just use `choco`  and then `msys-console.js` can be removed.

@dumol can you please take over this PR?

I was thinking to just remove `msys-console.js`  and make sure the current documentation is ok for @lgheorghiu to set up a new DEV environment in windows.

Thanks!

**Comment by dumol** [comment]
> This is not fixed as I was also trying to get rsync.
> 
> A brink version from this branch is already released and used in production.
> 
> I think that for dev, we now just use `choco` and then `msys-console.js` can be removed.
> 
> @dumol can you please take over this PR?
> 
> I was thinking to just remove `msys-console.js` and make sure the current documentation is ok for @lgheorghiu to set up a new DEV environment in windows.
> 
> Thanks!

I don't know what this is all about, but I'll take a look and try to finish it. Wish me luck! ;-]

**Comment by dumol** [comment]
OK, I've looked closer through the changes, this is a big PR. I understand it doesn't solve all the issues. But it does solve quite a few of them!

I suggest this should be merged in master, especially given there's already a released brink used in production.

Then I can look into simplifying things through Chocolatey and the other related goodies I used in `salt-master` repo for the Windows build slaves.

Adi, what say you?

**Comment by adiroiban** [comment]
@dumol I tried to update the code to get green build 

it looks like openbsd slave needs more space

I will merge it as it is, but when you have time, please look into the disk space issue.
Thanks!

**Comment by dumol** [comment]
> @dumol I tried to update the code to get green build
> 
> it looks like openbsd slave needs more space
> 
> I will merge it as it is, but when you have time, please look into the disk space issue.

Thanks! Solved the free space issue on the OpenBSD slave by using symlinks for `build*` and `cache`. 

There is still some bug that prevents using symlinks for `brink` repo, but it's unrelated to the issue I fixed in this branch. For the reference, `deps` phase fails with:
```
Installing base requirements: paver==1.2.4.
Requirement already satisfied: paver==1.2.4 in /srv/buildslave/runtime/build-openbsd65-x64/lib/python2.7/site-packages
You are using pip version 9.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/srv/buildslave/runtime/build-openbsd65-x64/slave/brink-obsd/build/build-openbsd65-x64/lib/python2.7/site-packages/paver/tasks.py", line 878, in main
    _launch_pavement(args)
  File "/srv/buildslave/runtime/build-openbsd65-x64/slave/brink-obsd/build/build-openbsd65-x64/lib/python2.7/site-packages/paver/tasks.py", line 846, in _launch_pavement
    exec(compile(source, environment.pavement_file, 'exec'), mod.__dict__)
  File "pavement.py", line 171, in <module>
    options.closure_linter['enabled'] = True
AttributeError: 'ScameOptions' object has no attribute 'closure_linter'
```

**Pull request merged**
