### PR TITLE
[#4071] Fix Unicode path passing on Windows/Mac OSX.

### PR DESCRIPTION
**Pull request by alibotean**
Scope
=====

The following error was displayed when running paver on Windows:

```
Exception:
Traceback (most recent call last):
  File "d:\_Work\chevah\server\build-windows-x86\lib\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "d:\_Work\chevah\server\build-windows-x86\lib\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "d:\_Work\chevah\server\build-windows-x86\lib\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "d:\_Work\chevah\server\build-windows-x86\lib\lib\site-packages\pip\req\req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "d:\_Work\chevah\server\build-windows-x86\lib\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "d:\_Work\chevah\server\build-windows-x86\lib\lib\site-packages\pip\wheel.py", line 272, in move_wheel_files
    compileall.compile_dir(source, force=True, quiet=True)
  File "d:\_Work\chevah\server\build-windows-x86\lib\lib\compileall.py", line 57, in compile_dir
    quiet):
  File "d:\_Work\chevah\server\build-windows-x86\lib\lib\compileall.py", line 57, in compile_dir
    quiet):
  File "d:\_Work\chevah\server\build-windows-x86\lib\lib\compileall.py", line 57, in compile_dir
    quiet):
  File "d:\_Work\chevah\server\build-windows-x86\lib\lib\compileall.py", line 57, in compile_dir
    quiet):
  File "d:\_Work\chevah\server\build-windows-x86\lib\lib\compileall.py", line 57, in compile_dir
    quiet):
  File "d:\_Work\chevah\server\build-windows-x86\lib\lib\compileall.py", line 50, in compile_dir
    if not compile_file(fullname, ddir, force, rx, quiet):
  File "d:\_Work\chevah\server\build-windows-x86\lib\lib\compileall.py", line 102, in compile_file
    print 'Compiling', fullname, '...'
TypeError: 'unicode' does not have the buffer interface
```

Changes
=======

For `Windows` and `Mac OSX` we are passing UTF-8 encoded values instead of Unicode.

How to try and test the changes
===============================

reviewers: @adiroiban @lgheorghiu @hcs0 

Please check that the changes make sense and the problem is not longer reproducible.

I have tested this on my machine and it works.

### CODE REVIEW

**Comment by alibotean** [comment]
I have noticed that the new brink is always downloading `astroid`:

```
Collecting astroid==1.3.6
  Downloading http://pypi.chevah.com/simple/astroid/astroid-1.3.6-py2.py3-none-any.whl (182kB)
    100% |################################| 184kB 1.5MB/s
```

**Comment by alibotean** [comment]
needs-review

**Comment by adiroiban** [comment]
@alibotean when requesting a review, make sure you are the owner of that ticket

needs-review

**Comment by alibotean** [comment]
I should have been, as I've:

1. assigned the ticket to myself (in Trac)
2. marked the ticket as started
3. created the PR, etc.

As far as I know my steps should have worked.

**Comment by alibotean** [comment]
I'm having issues publishing the new version:

```
creating build\bdist.win32\wheel\chevah_brink-0.61.3.dist-info\WHEEL
running upload
Traceback (most recent call last):
  File "setup.py", line 56, in <module>
    cmdclass={'publish': PublishCommand},
  File "H:\Projects\Chevah\brink\build-windows-x86\lib\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "H:\Projects\Chevah\brink\build-windows-x86\lib\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "H:\Projects\Chevah\brink\build-windows-x86\lib\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 39, in run
    self.run_command('upload')
  File "H:\Projects\Chevah\brink\build-windows-x86\lib\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "H:\Projects\Chevah\brink\build-windows-x86\lib\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "H:\Projects\Chevah\brink\build-windows-x86\lib\lib\distutils\command\upload.py", line 60, in run
    self.upload_file(command, pyversion, filename)
  File "H:\Projects\Chevah\brink\build-windows-x86\lib\lib\distutils\command\upload.py", line 70, in upload_file
    raise AssertionError("unsupported schema " + schema)
AssertionError: unsupported schema
```

**Comment by adiroiban** [comment]
I don't see any changes for the Windows platform

needs-changes

**Comment by alibotean** [comment]
```
  error: [Error 183] Cannot create a file when that file already exists: 'build\\bdist.win32\\wheel\\configparser-3.5.0b2.data\\..'

  ----------------------------------------
  Failed building wheel for configparser
Failed to build configparser
```

configparser  failes even if I've cleaned the distro first.

**Comment by alibotean** [comment]
> I don't see any changes for the Windows platform

You're right. The changes in this PR do not address the actual cause 👎

**Comment by alibotean** [comment]
I managed to find the problematic file:

```
H:\Projects\Chevah\brink\build-windows-x86\pip-build\astroid\
  H:\Projects\Chevah\brink\build-windows-x86\pip-build\astroid\astroid\tests\testdata\python3\data\module.py
```

I have no idea why `compileall.py` can't handke Unicode on Windows for this particular file. I can't see anything wrong with the path, it's plain old ASCII.

Until we have a better understanding/idea I've removed Windows from the list and we're using UTF-8 encoded paths instead of Unicode.

---

I don't know where to report this upstream:
* pip
* python
* astroid

**Comment by alibotean** [comment]
I've  also added the `build` folder to the ignore list as we're using it for `brink`.

**Comment by alibotean** [comment]
Please re-release; it should work. I've tested it on my machine. It no longer downloads astroid every time -- figures :smile:

**Comment by adiroiban** [comment]
> Until we have a better understanding/idea I've removed Windows from the list and we're using UTF-8 encoded paths instead of Unicode.

I don't know if that is ok... if we will have a non-ascii path, the Windows API might fail as it always need Unicode... so that it can decode it to UTF-16 which is the encoding using by the Windows API

------

I am not happy with the current proposed solution.

But, have you managed to reproduce this in a consistent manner ? For example using the brink project as an example.

**Comment by alibotean** [comment]
> But, have you managed to reproduce this in a consistent manner ? For example using the brink project as an example.

Yeap, I've done the testing on the `brink` project/repo.

It always fails at the same file, dependency with that error. It does not matter what the initial state is:

* existing distribution
* paver clean
* paver clean + cache removal

It always yields that error.

**Comment by adiroiban** [comment]
I was able to reproduce it on windows.

the problem is that astrid  has some py3 only code, which fails when compiled with py2.

compileall is designed to ignore such errors... and to only show an error... but it fails when it needs to show that error.

--------


The bug is in compileall and it should be fixed in python-package.

There is nothing to do in brink.

I will target this ticket to address the issue in python-package...and we can see if the patch is accepted upstream

-------

Thanks!

**Pull request closed without merging**
