### PR TITLE
[#2731] Accept changes-approved as alternative to approved-at latest

### PR DESCRIPTION
**Pull request by adiroiban**
Problem
======

When we use `approved-at latest` the developers needs to manually edit the comment before merge, this is stupid :)

Changes
=======

add a new 'changes-approved` command which does not care about the sha.

since we no longer check for sha, we need to check that there is no needs-changes newer than changes-approved

I have removed the `approved-at SHA` actions and they no longer work.

I have removed the dependency to chevah.github_hooks_server.handler as it was pooling to many other thinks.

Once this is merged we can remove  chevah-github-hooks-server from all other pavement.py files.

I also plan to create a separate package for buildbot_try so that we don't need the whole buildbot package for development. ... right now I see that the project pull about 77 dependencies for development ... since this is development is not a big deal but we can do better

as a drive by I have added a `--force-clean` option to pqm to allow cleaning the merge environment.

How to test
=========

reviewers: @dumol @alibotean @adiroiban

this is just to let you know about the changes.

approved the changes using the new `changes-approved` command
In case the code does not work, i should not be able to merge this.

I am also a reviewer just to test the code

thanks!

### CODE REVIEW

**Comment by adiroiban** [comment]
all good changes-approved

**Comment by adiroiban** [comment]
ignore comment

**Comment by adiroiban** [comment]
needs-changes

**Comment by adiroiban** [comment]
changes-approved

**Comment by adiroiban** [comment]
needs-review

**Comment by dumol** [comment]
Fine by me. But I'm not sure it's a good thing to lose the distinction between:

 a) approving changes for a certain SHA, thus denying the author to make more changes and
 b) approving _at latest_, which was a carte blanche from the reviewer to the author, allowing the later to make more changes before merging.

**changes-approved**

**Comment by adiroiban** [comment]
is ok for the author to make more changes... ie fix merge issues . we are all well intentioned and the idea of these approvals is to make it clear what is the status of the review.

**Comment by adiroiban** [comment]
beside fixing the PQM, I also need to fix the github-trac sync so recognize the new marker and update the tickets in trac... but this needs to be done in a separate project

**Comment by alibotean** [comment]
changes-approved

**Pull request closed without merging**
