### PR TITLE
[#2640] Fix clean task for rhel4.

### PR DESCRIPTION
**Pull request by adiroiban**
Problem
=======

Find from rhel 4 does not support +

Changes
========

Use simple print and xarg for RHEL4

How to test
=========

reviewers: @dumol 

run `paver test_remote rhel-4 --properties=force_clean=yes --wait` and see that  all is ok.

Thanks!

### CODE REVIEW

**Comment by adiroiban** [comment]
needs-review

**Comment by dumol** [comment]
I think we should simplify the tests for AIX and RHEL4 as follows:
```
case $OS in
    rhel4)
        touch dummy_file.pyc
        find ./ -name '*.pyc' -print0 | xargs -0 rm
    aix*)
        touch dummy_file.pyc
        find ./ -name '*.pyc' -exec rm {} +
    *)
        find ./ -name '*.pyc' -exec rm {} +
esac
```
Of course, keeping the relevant comments. This seems a bit more readable for me. What do you think?

**needs-review**

**Comment by dumol** [comment]
Sorry, I meant:

**needs-changes**

**Comment by adiroiban** [comment]
I have refactored the code.

I don't like your code as it repeats both the `touch` and `find +` command. Rule #1: Don't repeat yourself!

In my original and current version only touch command was repeated.

please let me know if you find the current version easier to read.

thanks!

 needs-review

**Comment by dumol** [comment]
It looks better, thanks! I would also change the name of the file created in RHEL4, but that's just a _minor touch_… :)

**approved-at latest**

**Pull request closed without merging**
