### PR TITLE
[#2617] Fix paver.sh for non-LSB x86 Linux.

### PR DESCRIPTION
**Pull request by dumol**
Problem?
----------
Current `paver.sh` fails on my netbook with Slackware because non-LSB Linux distros are equated with RHEL4 and we have no x86 Python package for RHEL4.

Solution?
-----------
Equate non-LSB Linux distros with Ubuntu 10.04, for which we already have an x86 Python package.

How to check?
-----------------
Please review changes.
Check `paver.sh` on a non-LSB Linux distro such as Slackware on x86 hardware.

reviewer: @adiroiban

### CODE REVIEW

**Comment by dumol** [comment]
**needs-review**

**Comment by adiroiban** [comment]
all good...
not sure if in these days slackware got support for PAM... but server should work even if there is no pam.

approved-at  83806f7

**Comment by dumol** [comment]
Well, no PAM installed here. But I managed to successfully start the server yesterday. Although `paver test` has thrown some error. Are you interested?

**Comment by adiroiban** [comment]
Yes. If you use slackware I think that we can put a slackware builslave and check that our products are ok on slackware. Thanks!

**Pull request closed without merging**
