### PR TITLE
[#3732] Add solaris10u3 detection to Paver

### PR DESCRIPTION
**Pull request by dispera**
Scope
=====

Implement Solaris 10u3 detection on paver.sh

Changes
=======

Added a variable to store the exact Solaris release, and a condition that checks if the release is 'solaris10u3'. In that case, it sends that to the OS variable, instead of the usual 'solaris10'.

How to try and test the changes
===============================

reviewers: @adiroiban 
You can check by running paver.sh detect_os on a Solaris10u3 system and checking the DEFAULT_VALUES file

### CODE REVIEW

**Comment by dispera** [comment]
needs-review

**Comment by adiroiban** [comment]
looks good, but please update the release-notes.rst with information about the changes.

I saw that this is not part of the README.rst so you might want to also update the readme to make it clear how to make changes to the repo.

thanks!

needs-changes

**Comment by dispera** [comment]
Ok I rebased from master and pulled/pushed to be up to date.

The rest is the solaris10u3 detection you already seen. Should be good to merge.

needs-review

**Comment by adiroiban** [comment]
Please, create a new branch with the ticket id in its name.

Don't know why the diff is strange... I was expeting to only see the solaris 10u3 change + release notes + setup.py changes

needs-changes

**Pull request closed without merging**
